name: CI

on:
  pull_request:
  push:

jobs:
  pre-commit:
    runs-on: ubuntu-latest
    steps:
      - uses: "actions/checkout@v3"
      - uses: actions/setup-python@v4
        with:
          python-version: "3.11"
      - uses: pre-commit/action@v3.0.1
  tests:
    name: "Test with python ${{ matrix.python-version }} on ${{ matrix.os }}"
    runs-on: ${{ matrix.machine }}
    strategy:
      matrix:
        include:
          - python-version: "3.6"
            machine: ubuntu-22.04
          - python-version: "3.7"
            machine: ubuntu-22.04
          - python-version: "3.8"
            machine: ubuntu-22.04
          - python-version: "3.10"
            machine: ubuntu-24.04
          - python-version: "3.11"
            machine: ubuntu-24.04
          - python-version: "3.12"
            machine: ubuntu-24.04
          - python-version: "3.13"
            machine: ubuntu-24.04
    steps:
      - uses: "actions/checkout@v4"
      - uses: "actions/setup-python@v5"
        with:
          python-version: "${{ matrix.python-version }}"
      - name: "Install dependencies"
        run: python -m pip install tox tox-gh-actions
      - name: "Run tox targets for ${{ matrix.python-version }}"
        run: python -m tox
      # lcov support not available in python 3.6
      - name: "Generate lcov report"
        run: python -m pip install coverage && python -m coverage lcov
        if: ${{ matrix.python-version != '3.6' }}
      - name: Coveralls
        uses: coverallsapp/github-action@v2
        if: ${{ matrix.python-version != '3.6' }}
        with:
          flag-name: run-${{ matrix.python-version }}
          parallel: true
  finish:
    needs: tests
    if: ${{ always() }}
    runs-on: ubuntu-latest
    steps:
    - name: Coveralls Finished
      uses: coverallsapp/github-action@v2
      with:
        parallel-finished: true
        carryforward: "run-3.7,run-3.8,run-3.9,run-3.10,run-3.11,run-3.12"
